name = "PathPlanningTools"
uuid = "7687b472-1afb-42b7-b5e5-1d8fde144a41"
authors = ["Michitoshi Tsubaki"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
